# Generated by Django 4.2 on 2024-04-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='tg'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vk',
            field=models.URLField(blank=True, null=True, verbose_name='vk'),
        ),
    ]
