# Generated by Django 4.2 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_about_customuser_telegram_customuser_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='tg'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vk',
            field=models.URLField(blank=True, default='', null=True, verbose_name='vk'),
        ),
    ]
