# Generated by Django 4.2 on 2024-04-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_about_alter_customuser_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='vk',
            field=models.URLField(blank=True, default='', verbose_name='vk'),
        ),
    ]
