# Generated by Django 4.2 on 2024-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_vk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.CharField(blank=True, default=0, verbose_name='exp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(blank=True, choices=[('Python-разработчик', 'Pd'), ('Java-разработчик', 'Jd'), ('Архитектор баз данных', 'Sql'), ('Аналитик', 'Analytic'), ('PHP-разработчик', 'Phpd'), ('C-разработчик', 'Cd')], default='', verbose_name='profession'),
        ),
    ]
