# Generated by Django 4.2 on 2024-04-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.TextField(blank=True, null=True)),
                ('offers', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
