# Generated by Django 4.2 on 2024-04-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='who_needs',
            field=models.CharField(choices=[('python', 'Python-разработчик'), ('java', 'Java-разработчик'), ('sql', 'Архитектор баз данных'), ('analytic', 'Аналитик'), ('php', 'PHP-разработчик'), ('c', 'C-разработчик')], default=''),
            preserve_default=False,
        ),
    ]
